name: Build WD package

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *

env:
  SRC_URL: https://github.com/WDCommunity/wdpksrc.git
  UPLOAD_FIRMWARE: true
  UPLOAD_RELEASE: true
  PACKAGES: docker entware
  TZ: Asia/Shanghai

jobs:
  Publish:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Initialization Environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        mkdir -p output/bin
        sudo -E apt-get -qq install libxml2 openssl
        pkgs=$PACKAGES
        echo "Packages: ${pkgs}"
        echo "PACKAGE=${pkgs}" >> $GITHUB_ENV

    - name: Download Src
      run: |
        git clone https://github.com/WDCommunity/wdpksrc.git
        cd wdpksrc

    - name: Make APKG packages for selected platforms
      id: make_apkg
      env:
        PLATFORM: ${{ matrix.platform }}
        MODEL: ${{ matrix.model }}
      run: |
        cd $GITHUB_WORKSPACE/wdpksrc
        pkg=$(echo ${PACKAGE:-docker} | cut -d' ' -f1)
        echo ::set-output name=pkg::"$pkg"
        cd wdpk/${pkg}
        DATE="$(date +"%m%d%Y")"
        CWD="$(pwd)"
        VERSION="$(awk '/Version/{print $NF}' apkg.rc)"
        echo ::set-output name=version::"${VERSION}"
        NAME="$(awk '/AddonShowName/{print $NF}' apkg.rc)"
        echo ::set-output name=name::"${NAME}"
        DESCRIPTION="$(awk '/Description/{print $NF}' apkg.rc)"
        echo ::set-output name=description::"${DESCRIPTION}"
        echo "Building ${pkg} version ${VERSION}"
        echo "$(ls -l ../..)"
        RELEASE_DIR="../../packages/${pkg}/OS5"
        mkdir -p "${RELEASE_DIR}"
        echo "PLF ${PLATFORM} - $arr - ${PACKAGE}"
        echo "Build ${pkg} for $MODEL"
        ../../mksapkg-OS5 -E -s -m ${PLATFORM} > /dev/null
        mv ../${PLATFORM}*.bin\(* ../${pkg}_${VERSION}_${MODEL}.bin
        echo "$(ls -l ..)"

    - name: Check space usage
      if: (!cancelled())
      run: df -hT

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ steps.make_apkg.outputs.pkg }}_${{ steps.make_apkg.outputs.version }}_OS5
        path: wdpk/*_*_*.bin

    - name: Generate release tag
      id: tag
      if: env.UPLOAD_RELEASE == 'true' && !cancelled()
      run: |
        echo "::set-output name=release_tag::$(date +"%Y.%m.%d-%H%M")"
        touch release.txt
        echo "WD My Cloud PKG"
        echo "::set-output name=status::success"

    - name: Upload packages to release
      uses: softprops/action-gh-release@v1
      if: steps.tag.outputs.status == 'success' && !cancelled()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tag.outputs.release_tag }}
        body_path: release.txt
        files: wdpk/*

    - name: Delete workflow runs
      uses: GitRML/delete-workflow-runs@main
      with:
        retain_days: 1
        keep_minimum_runs: 3

    - name: Remove old Releases
      uses: dev-drprasad/delete-older-releases@v0.1.0
      if: env.UPLOAD_RELEASE == 'true' && !cancelled()
      with:
        keep_latest: 3
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
